# Second ML Use Case "NBA Game Prediction"

***Can we predict the outcome of a game?***

* Decision Tree ML
* Repitition

## Step 0: Prerequisites

In [3]:
#importing all the relevant modules libaries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Step 1: Importing the Data

In [4]:
#importing the dataset

df = pd.read_csv('/Users/robertkurtz/Desktop/NBA 2023 Dataplayground/data/game.csv', delimiter=',')

In [5]:

pd.set_option('display.max_columns', None)
df.head(-5)

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,plus_minus_home,video_available_home,team_id_away,team_abbreviation_away,team_name_away,matchup_away,wl_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,NaN,NaN,NaN,NaN,NaN,16.0,29.0,0.552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66,-2,0,1610612752,NYK,New York Knicks,NYK @ HUS,W,24.0,NaN,NaN,NaN,NaN,NaN,20.0,26.0,0.769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68,2,0
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,59.0,0.339,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,56,5,0,1610610031,PIT,Pittsburgh Ironmen,PIT @ BOM,L,16.0,72.0,0.222,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,51,-5,0
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,NaN,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59,6,0,1610612738,BOS,Boston Celtics,BOS @ PRO,L,21.0,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53,-6,0
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,NaN,NaN,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,63,16,0,1610612752,NYK,New York Knicks,NYK @ CHS,L,16.0,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,47,-16,0
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,NaN,NaN,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33,-17,0,1610610036,WAS,Washington Capitols,WAS @ DEF,W,18.0,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50,17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62357,22022,1610612745,HOU,Houston Rockets,22201009,2023-03-11 00:00:00,HOU vs. CHI,L,240,41.0,85.0,0.482,16.0,34.0,0.471,13.0,17.0,0.765,6.0,27.0,33.0,28.0,10.0,3.0,16.0,19.0,111,-8,1,1610612741,CHI,Chicago Bulls,CHI @ HOU,W,44.0,86.0,0.512,15.0,32.0,0.469,16.0,22.0,0.727,13.0,31.0,44.0,25.0,7.0,9.0,14.0,17.0,119,8,1
62358,22022,1610612740,NOP,New Orleans Pelicans,22201011,2023-03-11 00:00:00,NOP vs. OKC,L,240,34.0,81.0,0.420,12.0,34.0,0.353,16.0,19.0,0.842,8.0,35.0,43.0,23.0,3.0,4.0,22.0,25.0,96,-14,1,1610612760,OKC,Oklahoma City Thunder,OKC @ NOP,W,37.0,80.0,0.463,9.0,28.0,0.321,27.0,32.0,0.844,4.0,34.0,38.0,17.0,11.0,2.0,12.0,17.0,110,14,1
62359,22022,1610612744,GSW,Golden State Warriors,22201012,2023-03-11 00:00:00,GSW vs. MIL,W,265,46.0,112.0,0.411,23.0,55.0,0.418,10.0,11.0,0.909,18.0,47.0,65.0,33.0,12.0,4.0,15.0,15.0,125,9,1,1610612749,MIL,Milwaukee Bucks,MIL @ GSW,L,43.0,100.0,0.430,21.0,51.0,0.412,9.0,11.0,0.818,7.0,41.0,48.0,28.0,9.0,7.0,17.0,14.0,116,-9,1
62360,22022,1610612756,PHX,Phoenix Suns,22201013,2023-03-11 00:00:00,PHX vs. SAC,L,240,44.0,89.0,0.494,13.0,44.0,0.295,18.0,22.0,0.818,7.0,33.0,40.0,30.0,11.0,3.0,14.0,26.0,119,-9,1,1610612758,SAC,Sacramento Kings,SAC @ PHX,W,41.0,85.0,0.482,15.0,35.0,0.429,31.0,37.0,0.838,8.0,31.0,39.0,19.0,10.0,2.0,15.0,19.0,128,9,1
62361,22022,1610612766,CHA,Charlotte Hornets,22201015,2023-03-12 00:00:00,CHA vs. CLE,L,240,41.0,80.0,0.513,10.0,21.0,0.476,16.0,22.0,0.727,7.0,36.0,43.0,25.0,8.0,5.0,19.0,26.0,108,-6,1,1610612739,CLE,Cleveland Cavaliers,CLE @ CHA,W,41.0,87.0,0.471,7.0,27.0,0.259,25.0,34.0,0.735,11.0,29.0,40.0,18.0,8.0,3.0,10.0,22.0,114,6,1

## Step 2: EDA

In [6]:
df.columns

Index(['season_id', 'team_id_home', 'team_abbreviation_home', 'team_name_home',
       'game_id', 'game_date', 'matchup_home', 'wl_home', 'min', 'fgm_home',
       'fga_home', 'fg_pct_home', 'fg3m_home', 'fg3a_home', 'fg3_pct_home',
       'ftm_home', 'fta_home', 'ft_pct_home', 'oreb_home', 'dreb_home',
       'reb_home', 'ast_home', 'stl_home', 'blk_home', 'tov_home', 'pf_home',
       'pts_home', 'plus_minus_home', 'video_available_home', 'team_id_away',
       'team_abbreviation_away', 'team_name_away', 'matchup_away', 'wl_away',
       'fgm_away', 'fga_away', 'fg_pct_away', 'fg3m_away', 'fg3a_away',
       'fg3_pct_away', 'ftm_away', 'fta_away', 'ft_pct_away', 'oreb_away',
       'dreb_away', 'reb_away', 'ast_away', 'stl_away', 'blk_away', 'tov_away',
       'pf_away', 'pts_away', 'plus_minus_away', 'video_available_away'],
      dtype='object')

In [7]:
#Dropping irrelevant columns

df.drop(['game_id','plus_minus_away','plus_minus_home','wl_away','pts_away','pts_home','matchup_home', 'matchup_away','team_id_home','team_id_away','team_abbreviation_home','video_available_home','team_abbreviation_away','video_available_away'], axis=1, inplace=True)
df.columns

Index(['season_id', 'team_name_home', 'game_date', 'wl_home', 'min',
       'fgm_home', 'fga_home', 'fg_pct_home', 'fg3m_home', 'fg3a_home',
       'fg3_pct_home', 'ftm_home', 'fta_home', 'ft_pct_home', 'oreb_home',
       'dreb_home', 'reb_home', 'ast_home', 'stl_home', 'blk_home', 'tov_home',
       'pf_home', 'team_name_away', 'fgm_away', 'fga_away', 'fg_pct_away',
       'fg3m_away', 'fg3a_away', 'fg3_pct_away', 'ftm_away', 'fta_away',
       'ft_pct_away', 'oreb_away', 'dreb_away', 'reb_away', 'ast_away',
       'stl_away', 'blk_away', 'tov_away', 'pf_away'],
      dtype='object')

In [8]:
df.shape

(62367, 40)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62367 entries, 0 to 62366
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season_id       62367 non-null  int64
 1   team_name_home  62367 non-null  object
 2   game_date       62367 non-null  object
 3   wl_home         62360 non-null  object
 4   min             62367 non-null  int64
 5   fgm_home        62349 non-null  float64
 6   fga_home        44505 non-null  float64
 7   fg_pct_home     44466 non-null  float64
 8   fg3m_home       46714 non-null  float64
 9   fg3a_home       41450 non-null  float64
 10  fg3_pct_home    41091 non-null  float64
 11  ftm_home        62346 non-null  float64
 12  fta_home        59331 non-null  float64
 13  ft_pct_home     59327 non-null  float64
 14  oreb_home       41164 non-null  float64
 15  dreb_home       41095 non-null  float64
 16  reb_home        44259 non-null  float64
 17  ast_home        44127 non-null  float64
 18  stl_home        41247 non-null  float64
 19  blk_home        41456 non-null  float64
 20  tov_home        41427 non-null  float64
 21  pf_home         59431 non-null  float64
 22  team_name_away  62367 non-null  object
 23  fgm_away        62352 non-null  float64
 24  fga_away        44506 non-null  float64
 25  fg_pct_away     44468 non-null  float64
 26  fg3m_away       46714 non-null  float64
 27  fg3a_away       41450 non-null  float64
 28  fg3_pct_away    41179 non-null  float64
 29  ftm_away        62352 non-null  float64
 30  fta_away        59334 non-null  float64
 31  ft_pct_away     59332 non-null  float64
 32  oreb_away       41164 non-null  float64
 33  dreb_away       41096 non-null  float64
 34  reb_away        44263 non-null  float64
 35  ast_away        44130 non-null  float64
 36  stl_away        41247 non-null  float64
 37  blk_away        41457 non-null  float64
 38  tov_away        41426 non-null  float64
 39  pf_away         59438 non-null  float64
dtypes: float64(34), int64(2), object(4)
memory usage: 19.0+ MB

In [10]:
#Checking for missing values
df.isnull().sum()

# dropping rows with missing values
df.dropna(inplace=True)
df.shape

(40663, 40)

A lot of rows has been deleted, because the oldest data cannot provide information on many columns

In [11]:
#changing the game_date format
df.game_date = pd.to_datetime(df.game_date)
df.head(1)

,season_id,team_name_home,game_date,wl_home,min,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,team_name_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away
17982,21981,Philadelphia 76ers,1982-01-23,W,240,39.0,97.0,0.402,1.0,1.0,1.0,21.0,35.0,0.6,25.0,21.0,60.0,22.0,11.0,3.0,18.0,29.0,Seattle SuperSonics,33.0,84.0,0.393,0.0,4.0,0.0,21.0,24.0,0.875,13.0,8.0,50.0,20.0,4.0,7.0,19.0,29.0

Dropping Seasons with smaller sample sizes (keep all above 1000 observations)

In [12]:
df.season_id.value_counts()

#dropping the season if value count is less than 1000

df = df[df.season_id.value_counts()[df.season_id].values > 1000]
df.season_id.value_counts() #checking if the code worked

22005    1230
22004    1230
22016    1230
22015    1230
22014    1230
22013    1230
22010    1230
22009    1230
22008    1230
22007    1230
22006    1230
22021    1230
22018    1230
22012    1229
22002    1189
22001    1189
22000    1189
21999    1189
21995    1189
22003    1189
21997    1188
21996    1188
21994    1107
21992    1103
21993    1102
21991    1098
22020    1080
21989    1067
21990    1064
22019    1059
22022    1012
Name: season_id, dtype: int64

In [13]:
#checking which season_id belongs to which season

df.season_id.value_counts().index

# Assuming the index is stored in the variable 'index'
index = pd.Index([22005, 22004, 22016, 22015, 22014, 22013, 22010, 22009, 22008,
                  22007, 22006, 22021, 22018, 22012, 22002, 22001, 22000, 21999,
                  21995, 22003, 21997, 21996, 21994, 21992, 21993, 21991, 22020,
                  21989, 21990, 22019, 22022], dtype='int64')

# Create an empty dictionary
season_dict = {}

# Iterate over the index and create key-value pairs in the dictionary
for season_id in index:
    season_start = str(season_id)[-2:]  # Extract the last 2 digits as the start year
    season_end = str(int(season_start) + 1).zfill(2)  # Calculate the end year as start year + 1
    season_year = f"{season_start}-{season_end}"  # Create the season year in the format "start-end"
    season_dict[season_id] = season_year

# Print the dictionary
print(season_dict)

{22005: '05-06', 22004: '04-05', 22016: '16-17', 22015: '15-16', 22014: '14-15', 22013: '13-14', 22010: '10-11', 22009: '09-10', 22008: '08-09', 22007: '07-08', 22006: '06-07', 22021: '21-22', 22018: '18-19', 22012: '12-13', 22002: '02-03', 22001: '01-02', 22000: '00-01', 21999: '99-100', 21995: '95-96', 22003: '03-04', 21997: '97-98', 21996: '96-97', 21994: '94-95', 21992: '92-93', 21993: '93-94', 21991: '91-92', 22020: '20-21', 21989: '89-90', 21990: '90-91', 22019: '19-20', 22022: '22-23'}

In [14]:
# Map the values of the season_id column using the dictionary and putting them next to season_id

df['season'] = df.season_id.map(season_dict)
df.head(1)

,season_id,team_name_home,game_date,wl_home,min,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,team_name_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,season
24122,21989,Miami Heat,1989-11-03,L,240,35.0,93.0,0.376,1.0,4.0,0.25,19.0,32.0,0.594,19.0,32.0,51.0,19.0,7.0,8.0,16.0,26.0,New Jersey Nets,38.0,86.0,0.442,1.0,6.0,0.167,33.0,37.0,0.892,10.0,40.0,50.0,20.0,7.0,10.0,14.0,25.0,89-90

replacing the season_id column with the new 'season' column

In [15]:
# Remove the "season_id" column
df.drop("season_id", axis=1, inplace=True)

# Get the column names of the DataFrame
columns = df.columns.tolist()

# Insert the "season" column at the first position
columns.insert(0, "season")

# Reorder the DataFrame with the new column order
df = df[columns]
df.head(1)

,season,team_name_home,game_date,wl_home,min,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,team_name_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,season
24122,89-90,Miami Heat,1989-11-03,L,240,35.0,93.0,0.376,1.0,4.0,0.25,19.0,32.0,0.594,19.0,32.0,51.0,19.0,7.0,8.0,16.0,26.0,New Jersey Nets,38.0,86.0,0.442,1.0,6.0,0.167,33.0,37.0,0.892,10.0,40.0,50.0,20.0,7.0,10.0,14.0,25.0,89-90

In [16]:
# drop season as we have now 2
# by dropping the first column it should do

df = df.iloc[:, 1:]

I want to change the order of the columns, to have everything much clearer...

In [17]:
desired_order = ['season', 'game_date','wl_home', 'team_name_home', 'team_name_away','min',
                 'fgm_home', 'fgm_away', 'fga_home', 'fga_away', 'fg_pct_home', 'fg_pct_away',
                 'fg3m_home', 'fg3m_away', 'fg3a_home', 'fg3a_away', 'fg3_pct_home', 'fg3_pct_away',
                 'ftm_home', 'ftm_away', 'fta_home', 'fta_away', 'ft_pct_home', 'ft_pct_away',
                 'oreb_home', 'oreb_away', 'dreb_home', 'dreb_away', 'reb_home', 'reb_away',
                 'ast_home', 'ast_away', 'stl_home', 'stl_away', 'blk_home', 'blk_away',
                 'tov_home', 'tov_away', 'pf_home', 'pf_away'
                 ]

df = df[desired_order]
df.head(1)

,season,game_date,wl_home,team_name_home,team_name_away,min,fgm_home,fgm_away,fga_home,fga_away,fg_pct_home,fg_pct_away,fg3m_home,fg3m_away,fg3a_home,fg3a_away,fg3_pct_home,fg3_pct_away,ftm_home,ftm_away,fta_home,fta_away,ft_pct_home,ft_pct_away,oreb_home,oreb_away,dreb_home,dreb_away,reb_home,reb_away,ast_home,ast_away,stl_home,stl_away,blk_home,blk_away,tov_home,tov_away,pf_home,pf_away
24122,89-90,1989-11-03,L,Miami Heat,New Jersey Nets,240,35.0,38.0,93.0,86.0,0.376,0.442,1.0,1.0,4.0,6.0,0.25,0.167,19.0,33.0,32.0,37.0,0.594,0.892,19.0,10.0,32.0,40.0,51.0,50.0,19.0,20.0,7.0,7.0,8.0,10.0,16.0,14.0,26.0,25.0

In [18]:
# give me the team name with most wins each season
#df.groupby('season')['wl_home'].value_counts()

In [19]:
# Preprocess the season column
df['season_start_year'] = df['season'].str.split('-').str[0].astype(int)

# Preprocess the game_date column
df['game_date'] = pd.to_datetime(df['game_date'])
df['game_year'] = df['game_date'].dt.year
df['game_month'] = df['game_date'].dt.month
df['game_day'] = df['game_date'].dt.day

In [20]:
# Convert 'wl_home' to a numerical variable
df['wl_home'] = df['wl_home'].map({'W': 1, 'L': 0})

## Step ?: Saving the preprocessed DF back into CSV

* this will be the one used for the model training in 03

In [21]:
# Specify the file path where you want to save the CSV file
file_path = '/Users/robertkurtz/Desktop/NBA 2023 Dataplayground/data/game_preprocessed.csv'

# Save the DataFrame to CSV format
df.to_csv(file_path, index=False)